apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer-service
  namespace: default
  labels:
    app: nginx-lb
spec:
  type: LoadBalancer  # Atau ClusterIP/NodePort sesuai kebutuhan
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx-lb
